
var nicEditEs = {
    'URL': 'URL',
    'Click to Bold': 'Negrita',
    'Click to Italic': 'Cursiva',
    'Click to Underline': 'Subrayado',
    'Left Align': 'Alinear a la izquierda',
    'Center Align': 'Centrar',
    'Right Align': 'Alinear a al derecha',
    'Justify Align': 'Justificar',
    'Insert Ordered List': 'Insertar lista ordenada',
    'Insert Unordered List': 'Insertar lista no ordenada',
    'Click to Subscript': 'Subíndice',
    'Click to Superscript': 'Superíndice',
    'Click to Strike Through': 'Tachado',
    'Remove Formatting': 'Eliminar formato',
    'Indent Text': 'Añadir sangría',
    'Remove Indent': 'Eliminar sangría',
    'Horizontal Rule': 'Línea horizontal',
    'Select Font Size': 'Seleccionar tamaño de fuente',
    'Select Font Family': 'Seleccionar tipo de fuente',
    'Select Font Format': 'Seleccionar formato de fuente',
    'Font&nbsp;Size...': 'Tamaño...',
    'Font&nbsp;Family...': 'Tipo...',
    'Font&nbsp;Format...': 'Formato...',
    'Paragraph': 'Párrafo',
    'Pre': 'Preformateado',
    'Heading&nbsp;6': 'Título&nbsp;6',
    'Heading&nbsp;5': 'Título&nbsp;5',
    'Heading&nbsp;4': 'Título&nbsp;4',
    'Heading&nbsp;3': 'Título&nbsp;3',
    'Heading&nbsp;2': 'Título&nbsp;2',
    'Heading&nbsp;1': 'Título&nbsp;1',
    'Add Link': 'Añadir enlace',
    'Remove Link': 'Eliminar enlace',
    'Add/Edit Link': 'Añadir/editar enlace',
    'Title': 'Título',
    'Open In': 'Abrir en',
    'Current Window': 'Ventana actual',
    'New Window': 'Nueva ventana',
    'You must enter a URL to Create a Link': 'Introduce la URL del enlace',
    'Change Text Color': 'Cambiar color del texto',
    'Change Background Color': 'Cambiar color de fondo',
    'Add Image': 'Añadir imagen',
    'Add/Edit Image': 'Añadir/editar imagen',
    'Alt Text': 'Texto alternativo',
    'Align': 'Alineamiento',
    'Default': 'Por defecto',
    'Left': 'Izquierda',
    'Right': 'Derecha',
    'You must enter a Image URL to insert': 'Selecciona la URL de la imagen',
    'Save this content': 'Guardar'
}

function __(s) {
    return nicEditEs[s] || s;
}